"""Master directory of fictional B2B SaaS customer companies.

This module defines the canonical identity for 35 companies that get seeded
across 12 source systems (Stripe, Salesforce, HubSpot, Intercom, Zendesk,
Slack, Notion, Gmail, PostHog, PagerDuty, Datadog, Sentry). Every seeder
reads from this file so cross-source JOINs work on natural keys.

The pre-allocated *_id fields are placeholders. After each seeder runs against
the real source API, the actual returned IDs replace these strings in the
runtime registry. The placeholders exist so downstream code can be written
against stable identifiers before seeding completes.
"""

from __future__ import annotations

import hashlib
from collections import Counter


COMPANIES: list[dict] = [
    {
        "slug": "acme-genomics",
        "name": "Acme Genomics",
        "industry": "Genomics / BioTech",
        "country": "USA",
        "employees": 312,
        "arr_minor": 14_800_000,
        "signup_date": "2023-04-18",
        "tier": "enterprise",
        "csm_owner_handle": "priya@us",
        "ae_owner_handle": "mark@us",
        "primary_contact_email": "ops@acme-genomics.example",
        "primary_contact_name": "Daniela Friedman, VP Platform Engineering",
        "finance_contact_email": "ar@acme-genomics.example",
        "billing_country_currency": "USD",
        "stripe_customer_id": "cus_FAKE_acme_gen_001",
        "salesforce_account_id": "001N00000ACMEGEN01",
        "hubspot_company_id": "8800110001",
        "intercom_contact_id": "ic_acme_gen_pc01",
        "notes": "Heavy compute consumer; runs Q3 sequencing pipeline that triples API usage Aug-Oct. Susan in finance disputes overages every cycle.",
    },
    {
        "slug": "acme-logistics",
        "name": "Acme Logistics",
        "industry": "Freight & Logistics",
        "country": "USA",
        "employees": 1480,
        "arr_minor": 38_500_000,
        "signup_date": "2022-09-02",
        "tier": "enterprise",
        "csm_owner_handle": "marcus@us",
        "ae_owner_handle": "sarah@us",
        "primary_contact_email": "platform@acme-logistics.example",
        "primary_contact_name": "Theodore Ngata, Director of FleetOps",
        "finance_contact_email": "billing@acme-logistics.example",
        "billing_country_currency": "USD",
        "stripe_customer_id": "cus_FAKE_acme_log_001",
        "salesforce_account_id": "001N00000ACMELOG01",
        "hubspot_company_id": "8800110002",
        "intercom_contact_id": "ic_acme_log_pc01",
        "notes": "NOT related to Acme Genomics despite shared name prefix - common confusion in support tickets. CFO wants quarterly true-up.",
    },
    {
        "slug": "helix-bio",
        "name": "Helix Bio",
        "industry": "Pharmaceutical Research",
        "country": "USA",
        "employees": 89,
        "arr_minor": 4_200_000,
        "signup_date": "2024-01-22",
        "tier": "pro",
        "csm_owner_handle": "priya@us",
        "ae_owner_handle": "mark@us",
        "primary_contact_email": "engineering@helix-bio.example",
        "primary_contact_name": "Ravi Subramanian, Head of Data",
        "finance_contact_email": "finance@helix-bio.example",
        "billing_country_currency": "USD",
        "stripe_customer_id": "cus_FAKE_helix_bio_001",
        "salesforce_account_id": "001N00000HELIXBIO1",
        "hubspot_company_id": "8800110003",
        "intercom_contact_id": "ic_helix_bio_pc01",
        "notes": "Early-stage; transitioned from starter Mar 2024. Watch for confusion with Helios Bio - different company, common typo.",
    },
    {
        "slug": "helios-bio",
        "name": "Helios Bio",
        "industry": "Clinical Diagnostics",
        "country": "USA",
        "employees": 245,
        "arr_minor": 11_900_000,
        "signup_date": "2023-07-11",
        "tier": "enterprise",
        "csm_owner_handle": "jenna@us",
        "ae_owner_handle": "sarah@us",
        "primary_contact_email": "ops@helios-bio.example",
        "primary_contact_name": "Marisol Pérez, Senior Engineering Manager",
        "finance_contact_email": "ap@helios-bio.example",
        "billing_country_currency": "USD",
        "stripe_customer_id": "cus_FAKE_helios_bio_001",
        "salesforce_account_id": "001N00000HELIOSBI1",
        "hubspot_company_id": "8800110004",
        "intercom_contact_id": "ic_helios_bio_pc01",
        "notes": "Frequently confused with Helix Bio (separate org). Sees consistent month-over-month growth, low support touch.",
    },
    {
        "slug": "lattice-robotics",
        "name": "Lattice Robotics",
        "industry": "Industrial Robotics",
        "country": "Germany",
        "employees": 620,
        "arr_minor": 27_400_000,
        "signup_date": "2022-11-30",
        "tier": "enterprise",
        "csm_owner_handle": "ingrid@eu",
        "ae_owner_handle": "klaus@eu",
        "primary_contact_email": "controls@lattice-robotics.example",
        "primary_contact_name": "Dr. Stefan Werner, Head of Control Systems",
        "finance_contact_email": "rechnungen@lattice-robotics.example",
        "billing_country_currency": "EUR",
        "stripe_customer_id": "cus_FAKE_lattice_rob_001",
        "salesforce_account_id": "001N00000LATTICER1",
        "hubspot_company_id": "8800110005",
        "intercom_contact_id": "ic_lattice_rob_pc01",
        "notes": "Strict VAT invoicing requirements. Procurement team insists on POs for every charge above EUR 5k.",
    },
    {
        "slug": "northwind-fintech",
        "name": "Northwind Fintech",
        "industry": "Embedded Finance",
        "country": "UK",
        "employees": 410,
        "arr_minor": 22_100_000,
        "signup_date": "2023-02-14",
        "tier": "enterprise",
        "csm_owner_handle": "ingrid@eu",
        "ae_owner_handle": "klaus@eu",
        "primary_contact_email": "platform@northwind-fintech.example",
        "primary_contact_name": "Olamide Adebayo, VP Engineering",
        "finance_contact_email": "finance@northwind-fintech.example",
        "billing_country_currency": "GBP",
        "stripe_customer_id": "cus_FAKE_northwind_001",
        "salesforce_account_id": "001N00000NORTHWND1",
        "hubspot_company_id": "8800110006",
        "intercom_contact_id": "ic_northwind_pc01",
        "notes": "Health: red. Three escalations in 2026 about webhook delivery SLAs. CSM weekly cadence in place.",
    },
    {
        "slug": "verdant-agritech",
        "name": "Verdant Agritech",
        "industry": "Precision Agriculture",
        "country": "USA",
        "employees": 156,
        "arr_minor": 7_800_000,
        "signup_date": "2023-06-08",
        "tier": "pro",
        "csm_owner_handle": "jenna@us",
        "ae_owner_handle": "elena@us",
        "primary_contact_email": "data@verdant-agritech.example",
        "primary_contact_name": "Wesley Tran, Director of Data Infrastructure",
        "finance_contact_email": "accounting@verdant-agritech.example",
        "billing_country_currency": "USD",
        "stripe_customer_id": "cus_FAKE_verdant_001",
        "salesforce_account_id": "001N00000VERDANT01",
        "hubspot_company_id": "8800110007",
        "intercom_contact_id": "ic_verdant_pc01",
        "notes": "Seasonal usage spikes during March planting season. Predictable, well-understood pattern.",
    },
    {
        "slug": "stratos-cloud",
        "name": "Stratos Cloud",
        "industry": "Cloud Infrastructure",
        "country": "USA",
        "employees": 980,
        "arr_minor": 49_500_000,
        "signup_date": "2022-05-19",
        "tier": "enterprise",
        "csm_owner_handle": "marcus@us",
        "ae_owner_handle": "sarah@us",
        "primary_contact_email": "billing-eng@stratos-cloud.example",
        "primary_contact_name": "Cassandra Whitfield, Principal Platform Architect",
        "finance_contact_email": "ar@stratos-cloud.example",
        "billing_country_currency": "USD",
        "stripe_customer_id": "cus_FAKE_stratos_001",
        "salesforce_account_id": "001N00000STRATOS01",
        "hubspot_company_id": "8800110008",
        "intercom_contact_id": "ic_stratos_pc01",
        "notes": "Largest single account. Custom contract with negotiated rate card. Any auto-applied price change is a billing incident.",
    },
    {
        "slug": "kaiju-games",
        "name": "Kaiju Games",
        "industry": "Mobile Gaming",
        "country": "Singapore",
        "employees": 78,
        "arr_minor": 3_400_000,
        "signup_date": "2024-08-03",
        "tier": "pro",
        "csm_owner_handle": "linh@apac",
        "ae_owner_handle": "wei@apac",
        "primary_contact_email": "backend@kaiju-games.example",
        "primary_contact_name": "Pemba Sherpa, Lead Backend Engineer",
        "finance_contact_email": "finops@kaiju-games.example",
        "billing_country_currency": "SGD",
        "stripe_customer_id": "cus_FAKE_kaiju_001",
        "salesforce_account_id": "001N00000KAIJU0001",
        "hubspot_company_id": "8800110009",
        "intercom_contact_id": "ic_kaiju_pc01",
        "notes": "Indie studio. Founder is the primary technical contact - prefers Slack to email.",
    },
    {
        "slug": "polaris-analytics",
        "name": "Polaris Analytics",
        "industry": "Marketing Analytics",
        "country": "Canada",
        "employees": 215,
        "arr_minor": 9_600_000,
        "signup_date": "2023-09-25",
        "tier": "pro",
        "csm_owner_handle": "priya@us",
        "ae_owner_handle": "elena@us",
        "primary_contact_email": "data-eng@polaris-analytics.example",
        "primary_contact_name": "Jean-Marc Ouellet, Data Platform Lead",
        "finance_contact_email": "ap@polaris-analytics.example",
        "billing_country_currency": "CAD",
        "stripe_customer_id": "cus_FAKE_polaris_001",
        "salesforce_account_id": "001N00000POLARIS01",
        "hubspot_company_id": "8800110010",
        "intercom_contact_id": "ic_polaris_pc01",
        "notes": "Recently expanded data warehouse - usage doubled in Q1 2026. Health: green, considering enterprise upgrade.",
    },
    {
        "slug": "tessera-health",
        "name": "Tessera Health",
        "industry": "Digital Health",
        "country": "USA",
        "employees": 540,
        "arr_minor": 31_200_000,
        "signup_date": "2022-08-15",
        "tier": "enterprise",
        "csm_owner_handle": "jenna@us",
        "ae_owner_handle": "mark@us",
        "primary_contact_email": "engineering@tessera-health.example",
        "primary_contact_name": "Anika Bhatnagar, VP Infrastructure",
        "finance_contact_email": "billing@tessera-health.example",
        "billing_country_currency": "USD",
        "stripe_customer_id": "cus_FAKE_tessera_001",
        "salesforce_account_id": "001N00000TESSERA01",
        "hubspot_company_id": "8800110011",
        "intercom_contact_id": "ic_tessera_pc01",
        "notes": "HIPAA BAA on file. Any audit-trail or data-handling tickets get fast-tracked. Compliance-heavy account.",
    },
    {
        "slug": "obsidian-security",
        "name": "Obsidian Security",
        "industry": "Cybersecurity / SOC",
        "country": "USA",
        "employees": 195,
        "arr_minor": 12_400_000,
        "signup_date": "2023-11-04",
        "tier": "enterprise",
        "csm_owner_handle": "marcus@us",
        "ae_owner_handle": "sarah@us",
        "primary_contact_email": "platform@obsidian-security.example",
        "primary_contact_name": "Logan Petrescu, Detection Engineering Director",
        "finance_contact_email": "ar@obsidian-security.example",
        "billing_country_currency": "USD",
        "stripe_customer_id": "cus_FAKE_obsidian_001",
        "salesforce_account_id": "001N00000OBSIDIAN1",
        "hubspot_company_id": "8800110012",
        "intercom_contact_id": "ic_obsidian_pc01",
        "notes": "Procurement requires SOC2 Type II evidence annually. Renewal in Nov - expansion conversation underway.",
    },
    {
        "slug": "marigold-payments",
        "name": "Marigold Payments",
        "industry": "Payments / Fintech",
        "country": "India",
        "employees": 730,
        "arr_minor": 18_600_000,
        "signup_date": "2023-03-21",
        "tier": "enterprise",
        "csm_owner_handle": "linh@apac",
        "ae_owner_handle": "wei@apac",
        "primary_contact_email": "platform@marigold-payments.example",
        "primary_contact_name": "Devika Iyer, Head of Engineering",
        "finance_contact_email": "finance@marigold-payments.example",
        "billing_country_currency": "INR",
        "stripe_customer_id": "cus_FAKE_marigold_001",
        "salesforce_account_id": "001N00000MARIGOLD1",
        "hubspot_company_id": "8800110013",
        "intercom_contact_id": "ic_marigold_pc01",
        "notes": "GST handling on every invoice. Finance team needs PAN and HSN code on all line items - non-negotiable.",
    },
    {
        "slug": "harborlight-shipping",
        "name": "Harborlight Shipping",
        "industry": "Maritime Logistics",
        "country": "UK",
        "employees": 385,
        "arr_minor": 14_300_000,
        "signup_date": "2022-12-08",
        "tier": "enterprise",
        "csm_owner_handle": "ingrid@eu",
        "ae_owner_handle": "klaus@eu",
        "primary_contact_email": "ops@harborlight-shipping.example",
        "primary_contact_name": "Bernard Sinclair, Head of Vessel Tracking",
        "finance_contact_email": "ap@harborlight-shipping.example",
        "billing_country_currency": "GBP",
        "stripe_customer_id": "cus_FAKE_harborlight_001",
        "salesforce_account_id": "001N00000HARBORL01",
        "hubspot_company_id": "8800110014",
        "intercom_contact_id": "ic_harborlight_pc01",
        "notes": "Renamed from 'Harbour Light Shipping Ltd' in Jan 2026. Older invoices/records still reference old name - flag for reconciliation.",
    },
    {
        "slug": "redshift-edu",
        "name": "Redshift Education",
        "industry": "EdTech / K-12",
        "country": "USA",
        "employees": 124,
        "arr_minor": 5_400_000,
        "signup_date": "2024-04-09",
        "tier": "pro",
        "csm_owner_handle": "jenna@us",
        "ae_owner_handle": "elena@us",
        "primary_contact_email": "tech@redshift-edu.example",
        "primary_contact_name": "Greta Holcomb, CTO",
        "finance_contact_email": "controller@redshift-edu.example",
        "billing_country_currency": "USD",
        "stripe_customer_id": "cus_FAKE_redshift_001",
        "salesforce_account_id": "001N00000REDSHIFT1",
        "hubspot_company_id": "8800110015",
        "intercom_contact_id": "ic_redshift_pc01",
        "notes": "Academic-year usage cycle - big drop in usage June-August. Finance prefers quarterly billing.",
    },
    {
        "slug": "vantage-realty",
        "name": "Vantage Realty",
        "industry": "Proptech",
        "country": "Australia",
        "employees": 290,
        "arr_minor": 9_100_000,
        "signup_date": "2023-05-30",
        "tier": "pro",
        "csm_owner_handle": "linh@apac",
        "ae_owner_handle": "wei@apac",
        "primary_contact_email": "platform@vantage-realty.example",
        "primary_contact_name": "Hugh Pemberton, Director of Engineering",
        "finance_contact_email": "accounts@vantage-realty.example",
        "billing_country_currency": "AUD",
        "stripe_customer_id": "cus_FAKE_vantage_001",
        "salesforce_account_id": "001N00000VANTAGE01",
        "hubspot_company_id": "8800110016",
        "intercom_contact_id": "ic_vantage_pc01",
        "notes": "Active in Sydney + Melbourne markets. GST invoicing required. Generally low-touch account.",
    },
    {
        "slug": "ironforge-manufacturing",
        "name": "Ironforge Manufacturing",
        "industry": "Industrial IoT",
        "country": "Germany",
        "employees": 1850,
        "arr_minor": 41_200_000,
        "signup_date": "2022-07-04",
        "tier": "enterprise",
        "csm_owner_handle": "ingrid@eu",
        "ae_owner_handle": "klaus@eu",
        "primary_contact_email": "iiot@ironforge-mfg.example",
        "primary_contact_name": "Dr. Heinrich Vollmer, VP Industrial IoT",
        "finance_contact_email": "rechnungen@ironforge-mfg.example",
        "billing_country_currency": "EUR",
        "stripe_customer_id": "cus_FAKE_ironforge_001",
        "salesforce_account_id": "001N00000IRONFRGE1",
        "hubspot_company_id": "8800110017",
        "intercom_contact_id": "ic_ironforge_pc01",
        "notes": "Health: yellow. Renewal discussions stalled around price increase. Watch for churn risk Q4.",
    },
    {
        "slug": "saffron-grocery",
        "name": "Saffron Grocery",
        "industry": "Grocery Tech / Last-Mile",
        "country": "India",
        "employees": 470,
        "arr_minor": 8_700_000,
        "signup_date": "2024-02-26",
        "tier": "pro",
        "csm_owner_handle": "linh@apac",
        "ae_owner_handle": "wei@apac",
        "primary_contact_email": "tech@saffron-grocery.example",
        "primary_contact_name": "Aarav Malhotra, Head of Backend",
        "finance_contact_email": "ap@saffron-grocery.example",
        "billing_country_currency": "INR",
        "stripe_customer_id": "cus_FAKE_saffron_001",
        "salesforce_account_id": "001N00000SAFFRON01",
        "hubspot_company_id": "8800110018",
        "intercom_contact_id": "ic_saffron_pc01",
        "notes": "Festival-season volume spikes (Diwali, Eid) tripled API calls in Oct 2025. Predictive scaling conversation underway.",
    },
    {
        "slug": "ember-creative",
        "name": "Ember Creative",
        "industry": "Creative SaaS / Design Tools",
        "country": "USA",
        "employees": 52,
        "arr_minor": 1_900_000,
        "signup_date": "2025-01-15",
        "tier": "starter",
        "csm_owner_handle": "jenna@us",
        "ae_owner_handle": "elena@us",
        "primary_contact_email": "engineering@ember-creative.example",
        "primary_contact_name": "Mia Castellano, Engineering Manager",
        "finance_contact_email": "ops@ember-creative.example",
        "billing_country_currency": "USD",
        "stripe_customer_id": "cus_FAKE_ember_001",
        "salesforce_account_id": "001N00000EMBER0001",
        "hubspot_company_id": "8800110019",
        "intercom_contact_id": "ic_ember_pc01",
        "notes": "Self-serve signup. Growing fast - PLG funnel candidate for pro tier conversation by mid-2026.",
    },
    {
        "slug": "cobalt-medical",
        "name": "Cobalt Medical Devices",
        "industry": "MedTech",
        "country": "USA",
        "employees": 680,
        "arr_minor": 26_800_000,
        "signup_date": "2022-10-12",
        "tier": "enterprise",
        "csm_owner_handle": "marcus@us",
        "ae_owner_handle": "mark@us",
        "primary_contact_email": "platform@cobalt-medical.example",
        "primary_contact_name": "Dr. Imani Walker, Director of Software Engineering",
        "finance_contact_email": "ar@cobalt-medical.example",
        "billing_country_currency": "USD",
        "stripe_customer_id": "cus_FAKE_cobalt_001",
        "salesforce_account_id": "001N00000COBALT001",
        "hubspot_company_id": "8800110020",
        "intercom_contact_id": "ic_cobalt_pc01",
        "notes": "FDA-regulated environment - audit trail requirements are strict. Annual compliance review baked into renewal cycle.",
    },
    {
        "slug": "fjord-design",
        "name": "Fjord Design Studio",
        "industry": "Design SaaS",
        "country": "USA",
        "employees": 38,
        "arr_minor": 950_000,
        "signup_date": "2026-02-10",
        "tier": "starter",
        "csm_owner_handle": "jenna@us",
        "ae_owner_handle": "elena@us",
        "primary_contact_email": "founders@fjord-design.example",
        "primary_contact_name": "Eirik Halvorsen, Co-founder & CTO",
        "finance_contact_email": "founders@fjord-design.example",
        "billing_country_currency": "USD",
        "stripe_customer_id": "cus_FAKE_fjord_001",
        "salesforce_account_id": "001N00000FJORD0001",
        "hubspot_company_id": "8800110021",
        "intercom_contact_id": "ic_fjord_pc01",
        "notes": "Early-stage startup. Founder is the only technical contact. Card on file, no negotiated terms.",
    },
    {
        "slug": "monsoon-travel",
        "name": "Monsoon Travel",
        "industry": "Travel Tech",
        "country": "Singapore",
        "employees": 165,
        "arr_minor": 6_300_000,
        "signup_date": "2023-10-17",
        "tier": "pro",
        "csm_owner_handle": "linh@apac",
        "ae_owner_handle": "wei@apac",
        "primary_contact_email": "platform@monsoon-travel.example",
        "primary_contact_name": "Siti Rahman, Head of Platform Engineering",
        "finance_contact_email": "finance@monsoon-travel.example",
        "billing_country_currency": "SGD",
        "stripe_customer_id": "cus_FAKE_monsoon_001",
        "salesforce_account_id": "001N00000MONSOON01",
        "hubspot_company_id": "8800110022",
        "intercom_contact_id": "ic_monsoon_pc01",
        "notes": "Booking volume seasonal - Dec/Jan peak. Considers itself underpriced vs usage tier, may renegotiate.",
    },
    {
        "slug": "quartzline-energy",
        "name": "Quartzline Energy",
        "industry": "CleanTech / Renewables",
        "country": "Germany",
        "employees": 425,
        "arr_minor": 16_700_000,
        "signup_date": "2023-08-14",
        "tier": "enterprise",
        "csm_owner_handle": "ingrid@eu",
        "ae_owner_handle": "klaus@eu",
        "primary_contact_email": "engineering@quartzline-energy.example",
        "primary_contact_name": "Annelise Brückner, VP Grid Software",
        "finance_contact_email": "rechnungen@quartzline-energy.example",
        "billing_country_currency": "EUR",
        "stripe_customer_id": "cus_FAKE_quartzline_001",
        "salesforce_account_id": "001N00000QUARTZ001",
        "hubspot_company_id": "8800110023",
        "intercom_contact_id": "ic_quartzline_pc01",
        "notes": "Energy-sector compliance overhead is high. ESG reporting integration in conversation for late 2026.",
    },
    {
        "slug": "mockingbird-media",
        "name": "Mockingbird Media",
        "industry": "Streaming / Media Tech",
        "country": "USA",
        "employees": 320,
        "arr_minor": 13_500_000,
        "signup_date": "2022-06-20",
        "tier": "enterprise",
        "csm_owner_handle": "priya@us",
        "ae_owner_handle": "sarah@us",
        "primary_contact_email": "platform@mockingbird-media.example",
        "primary_contact_name": "Damon Reyes, Director of Streaming Infrastructure",
        "finance_contact_email": "billing@mockingbird-media.example",
        "billing_country_currency": "USD",
        "stripe_customer_id": "cus_FAKE_mockingbird_001",
        "salesforce_account_id": "001N00000MOCKBIRD1",
        "hubspot_company_id": "8800110024",
        "intercom_contact_id": "ic_mockingbird_pc01",
        "notes": "Migration pair with mockingbird-media-legacy slug. Both stripe records active during reconciliation - merge planned.",
        "migration_pair_slug": "mockingbird-media-legacy",
    },
    {
        "slug": "mockingbird-media-legacy",
        "name": "Mockingbird Media",
        "industry": "Streaming / Media Tech",
        "country": "USA",
        "employees": 320,
        "arr_minor": 0,
        "signup_date": "2021-03-08",
        "tier": "enterprise",
        "csm_owner_handle": "priya@us",
        "ae_owner_handle": "sarah@us",
        "primary_contact_email": "platform-old@mockingbird-media.example",
        "primary_contact_name": "Damon Reyes, Director of Streaming Infrastructure",
        "finance_contact_email": "billing@mockingbird-media.example",
        "billing_country_currency": "USD",
        "stripe_customer_id": "cus_FAKE_mockingbird_LEGACY",
        "salesforce_account_id": "001N00000MOCKBIRDL",
        "hubspot_company_id": "8800110025",
        "intercom_contact_id": "ic_mockingbird_legacy",
        "notes": "Migration pair with mockingbird-media. Legacy stripe customer from pre-2022 platform. Should be closed but still has open subscription tail.",
        "migration_pair_slug": "mockingbird-media",
    },
    {
        "slug": "trellis-hr",
        "name": "Trellis HR",
        "industry": "HR Tech",
        "country": "Canada",
        "employees": 98,
        "arr_minor": 3_700_000,
        "signup_date": "2024-05-11",
        "tier": "pro",
        "csm_owner_handle": "priya@us",
        "ae_owner_handle": "elena@us",
        "primary_contact_email": "engineering@trellis-hr.example",
        "primary_contact_name": "Chloé Beaumont, Head of Engineering",
        "finance_contact_email": "ap@trellis-hr.example",
        "billing_country_currency": "CAD",
        "stripe_customer_id": "cus_FAKE_trellis_001",
        "salesforce_account_id": "001N00000TRELLIS01",
        "hubspot_company_id": "8800110026",
        "intercom_contact_id": "ic_trellis_pc01",
        "notes": "Quebec billing - French invoice translations required. Account team coordinates with localization for tax language.",
    },
    {
        "slug": "ozone-delivery",
        "name": "Ozone Delivery",
        "industry": "Last-Mile Delivery",
        "country": "USA",
        "employees": 760,
        "arr_minor": 21_400_000,
        "signup_date": "2022-04-25",
        "tier": "enterprise",
        "csm_owner_handle": "marcus@us",
        "ae_owner_handle": "mark@us",
        "primary_contact_email": "ops-platform@ozone-delivery.example",
        "primary_contact_name": "Tobias Kane, VP Operations Tech",
        "finance_contact_email": "ar@ozone-delivery.example",
        "billing_country_currency": "USD",
        "stripe_customer_id": "cus_FAKE_ozone_001",
        "salesforce_account_id": "001N00000OZONE0001",
        "hubspot_company_id": "8800110027",
        "intercom_contact_id": "ic_ozone_pc01",
        "notes": "Health: red. Q1 2026 incident caused 6-hour outage on their dispatch service. Trust rebuild in progress - exec sponsor weekly check-ins.",
    },
    {
        "slug": "harvest-payroll",
        "name": "Harvest Payroll",
        "industry": "Payroll & Workforce",
        "country": "USA",
        "employees": 220,
        "arr_minor": 8_400_000,
        "signup_date": "2023-12-19",
        "tier": "pro",
        "csm_owner_handle": "jenna@us",
        "ae_owner_handle": "elena@us",
        "primary_contact_email": "platform@harvest-payroll.example",
        "primary_contact_name": "Yusuf Demir, Engineering Director",
        "finance_contact_email": "billing@harvest-payroll.example",
        "billing_country_currency": "USD",
        "stripe_customer_id": "cus_FAKE_harvest_001",
        "salesforce_account_id": "001N00000HARVEST01",
        "hubspot_company_id": "8800110028",
        "intercom_contact_id": "ic_harvest_pc01",
        "notes": "Monthly pay-cycle spikes are predictable. Health: green. Considering API tier upgrade for expanded SDK use.",
    },
    {
        "slug": "thorn-vc",
        "name": "Thorn Capital",
        "industry": "Venture Capital / Portfolio Ops",
        "country": "USA",
        "employees": 41,
        "arr_minor": 2_200_000,
        "signup_date": "2024-09-18",
        "tier": "pro",
        "csm_owner_handle": "priya@us",
        "ae_owner_handle": "elena@us",
        "primary_contact_email": "tech@thorn-capital.example",
        "primary_contact_name": "Veronica Ashworth, Head of Portfolio Tech",
        "finance_contact_email": "operations@thorn-capital.example",
        "billing_country_currency": "USD",
        "stripe_customer_id": "cus_FAKE_thorn_001",
        "salesforce_account_id": "001N00000THORN0001",
        "hubspot_company_id": "8800110029",
        "intercom_contact_id": "ic_thorn_pc01",
        "notes": "Boutique VC firm - low usage but very high LTV expectation. Quarterly business review with managing partner.",
    },
    {
        "slug": "lumen-edtech",
        "name": "Lumen EdTech",
        "industry": "EdTech / Higher Ed",
        "country": "UK",
        "employees": 145,
        "arr_minor": 5_900_000,
        "signup_date": "2023-01-30",
        "tier": "pro",
        "csm_owner_handle": "ingrid@eu",
        "ae_owner_handle": "klaus@eu",
        "primary_contact_email": "engineering@lumen-edtech.example",
        "primary_contact_name": "Sebastian Whitlock, Lead Platform Engineer",
        "finance_contact_email": "accounts@lumen-edtech.example",
        "billing_country_currency": "GBP",
        "stripe_customer_id": "cus_FAKE_lumen_001",
        "salesforce_account_id": "001N00000LUMEN0001",
        "hubspot_company_id": "8800110030",
        "intercom_contact_id": "ic_lumen_pc01",
        "notes": "University clients - academic-year billing alignment requested. CSM working on custom invoicing schedule.",
    },
    {
        "slug": "atlas-logistics",
        "name": "Atlas Logistics Group",
        "industry": "Supply Chain Tech",
        "country": "Italy",
        "employees": 510,
        "arr_minor": 19_300_000,
        "signup_date": "2022-11-15",
        "tier": "enterprise",
        "csm_owner_handle": "ingrid@eu",
        "ae_owner_handle": "klaus@eu",
        "primary_contact_email": "tech@atlas-logistics.example",
        "primary_contact_name": "Giovanni Moretti, Direttore Piattaforma",
        "finance_contact_email": "fatturazione@atlas-logistics.example",
        "billing_country_currency": "EUR",
        "stripe_customer_id": "cus_FAKE_atlas_001",
        "salesforce_account_id": "001N00000ATLAS0001",
        "hubspot_company_id": "8800110031",
        "intercom_contact_id": "ic_atlas_pc01",
        "notes": "Italian PEC e-invoicing requirements. Codice Destinatario and SDI integration handled in seller's accounting system.",
    },
    {
        "slug": "pixelmint-studios",
        "name": "Pixelmint Studios",
        "industry": "Gaming / Mobile",
        "country": "USA",
        "employees": 64,
        "arr_minor": 2_500_000,
        "signup_date": "2024-11-08",
        "tier": "starter",
        "csm_owner_handle": "jenna@us",
        "ae_owner_handle": "elena@us",
        "primary_contact_email": "backend@pixelmint.example",
        "primary_contact_name": "Skylar Rojas-Kim, Backend Lead",
        "finance_contact_email": "ops@pixelmint.example",
        "billing_country_currency": "USD",
        "stripe_customer_id": "cus_FAKE_pixelmint_001",
        "salesforce_account_id": "001N00000PIXELMNT1",
        "hubspot_company_id": "8800110032",
        "intercom_contact_id": "ic_pixelmint_pc01",
        "notes": "Indie game studio. Recently shipped a hit title - usage 4x over last 60 days. Upgrade conversation warming up.",
    },
    {
        "slug": "borealis-iot",
        "name": "Borealis IoT",
        "industry": "Industrial IoT / Energy",
        "country": "Canada",
        "employees": 178,
        "arr_minor": 7_100_000,
        "signup_date": "2023-04-02",
        "tier": "pro",
        "csm_owner_handle": "priya@us",
        "ae_owner_handle": "mark@us",
        "primary_contact_email": "platform@borealis-iot.example",
        "primary_contact_name": "Naomi Lavoie, VP Engineering",
        "finance_contact_email": "ar@borealis-iot.example",
        "billing_country_currency": "CAD",
        "stripe_customer_id": "cus_FAKE_borealis_001",
        "salesforce_account_id": "001N00000BOREALS01",
        "hubspot_company_id": "8800110033",
        "intercom_contact_id": "ic_borealis_pc01",
        "notes": "Remote oilfield deployments mean lots of intermittent connectivity. Webhook retry logic critical - tickets reflect that.",
    },
    {
        "slug": "sundial-restaurants",
        "name": "Sundial Restaurant Group",
        "industry": "Restaurant Tech / SaaS-for-Hospitality",
        "country": "Australia",
        "employees": 92,
        "arr_minor": 3_100_000,
        "signup_date": "2024-07-19",
        "tier": "pro",
        "csm_owner_handle": "linh@apac",
        "ae_owner_handle": "wei@apac",
        "primary_contact_email": "tech@sundial-rg.example",
        "primary_contact_name": "Owen Carmichael, Head of Engineering",
        "finance_contact_email": "accounts@sundial-rg.example",
        "billing_country_currency": "AUD",
        "stripe_customer_id": "cus_FAKE_sundial_001",
        "salesforce_account_id": "001N00000SUNDIAL01",
        "hubspot_company_id": "8800110034",
        "intercom_contact_id": "ic_sundial_pc01",
        "notes": "60-location restaurant group rolling out POS integration. Pilot phase - support touch heavy until end of Q2 2026.",
    },
    {
        "slug": "veritas-legal",
        "name": "Veritas Legal Tech",
        "industry": "LegalTech",
        "country": "USA",
        "employees": 134,
        "arr_minor": 6_800_000,
        "signup_date": "2023-07-26",
        "tier": "pro",
        "csm_owner_handle": "marcus@us",
        "ae_owner_handle": "sarah@us",
        "primary_contact_email": "engineering@veritas-legal.example",
        "primary_contact_name": "Priscilla Hammond, Senior Engineering Director",
        "finance_contact_email": "billing@veritas-legal.example",
        "billing_country_currency": "USD",
        "stripe_customer_id": "cus_FAKE_veritas_001",
        "salesforce_account_id": "001N00000VERITAS01",
        "hubspot_company_id": "8800110035",
        "intercom_contact_id": "ic_veritas_pc01",
        "notes": "Document confidentiality requirements - strict access controls audited every quarter by their compliance team.",
    },
]


def by_slug(slug: str) -> dict | None:
    """Return the company dict with the given slug, or None if not found."""
    for company in COMPANIES:
        if company["slug"] == slug:
            return company
    return None


def by_email(email: str) -> dict | None:
    """Return the first company matching email in any contact field, or None."""
    email_lower = email.strip().lower()
    for company in COMPANIES:
        if (
            company["primary_contact_email"].lower() == email_lower
            or company["finance_contact_email"].lower() == email_lower
        ):
            return company
    return None


def random_other_company(seed: int = 0) -> dict:
    """Deterministically pick a 'noise' company given a seed integer.

    Useful for generating cross-company noise (e.g. a stray email from an
    unrelated account) where you want reproducible-but-varied selection.
    """
    digest = hashlib.sha256(str(seed).encode("utf-8")).digest()
    idx = int.from_bytes(digest[:4], "big") % len(COMPANIES)
    return COMPANIES[idx]


def companies_in_industry(industry: str) -> list[dict]:
    """Return all companies whose industry string contains the given term (case-insensitive)."""
    needle = industry.strip().lower()
    return [c for c in COMPANIES if needle in c["industry"].lower()]


if __name__ == "__main__":
    import json

    print("=== First 5 companies ===")
    for company in COMPANIES[:5]:
        print(json.dumps(company, indent=2))
        print()

    print("=== Summary ===")
    print(f"Total companies: {len(COMPANIES)}")

    tier_counts = Counter(c["tier"] for c in COMPANIES)
    print("\nBy tier:")
    for tier, count in sorted(tier_counts.items()):
        print(f"  {tier}: {count}")

    country_counts = Counter(c["country"] for c in COMPANIES)
    print("\nBy country:")
    for country, count in sorted(country_counts.items(), key=lambda x: (-x[1], x[0])):
        print(f"  {country}: {count}")

    industry_counts = Counter(c["industry"] for c in COMPANIES)
    print(f"\nUnique industries: {len(industry_counts)}")

    currency_counts = Counter(c["billing_country_currency"] for c in COMPANIES)
    print("\nBy currency:")
    for currency, count in sorted(currency_counts.items(), key=lambda x: (-x[1], x[0])):
        print(f"  {currency}: {count}")

    total_arr = sum(c["arr_minor"] for c in COMPANIES)
    print(f"\nTotal ARR (minor units): {total_arr:,}")
    print(f"Mean ARR (minor units):  {total_arr // len(COMPANIES):,}")
    print(f"Min ARR (minor units):   {min(c['arr_minor'] for c in COMPANIES):,}")
    print(f"Max ARR (minor units):   {max(c['arr_minor'] for c in COMPANIES):,}")

    migration_pairs = [c for c in COMPANIES if "migration_pair_slug" in c]
    print(f"\nMigration pairs: {len(migration_pairs)} records")
    for c in migration_pairs:
        print(f"  {c['slug']} <-> {c['migration_pair_slug']}")
