-- Clicky citation reasoning cache.
--
-- When the operator clicks an inline citation chip in the Brief, the UI
-- fetches a "why this source record matters" explanation generated by
-- Gemini Flash 3.1 Lite using the case context + the finding text.
-- We cache so a chip clicked twice doesn't pay the LLM cost twice.
--
-- Keyed by (org, case, source, table, ref, field). Field is part of the
-- key because the same row referenced via two different fields can
-- support two different findings ("the customer's email" vs "the
-- customer's account creation date" both on stripe.customers/cus_xxx).

CREATE TABLE IF NOT EXISTS citation_reasonings (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    org_id          UUID NOT NULL REFERENCES orgs(id) ON DELETE CASCADE,
    case_id         UUID NOT NULL REFERENCES cases(id) ON DELETE CASCADE,
    source          TEXT NOT NULL,
    table_name      TEXT NOT NULL,
    ref             TEXT NOT NULL,
    field           TEXT NOT NULL DEFAULT '',
    reasoning       TEXT NOT NULL,           -- 2-3 plain-English sentences
    model           TEXT,                    -- which model produced it
    generated_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- One reasoning per (case, source, table, ref, field). The empty-string
-- default on `field` makes the unique index work cleanly even when the
-- citation didn't pin a field.
CREATE UNIQUE INDEX IF NOT EXISTS uniq_citation_reasonings
    ON citation_reasonings (org_id, case_id, source, table_name, ref, field);

-- Fast lookup by case_id (UI fetches all reasonings for a case on
-- workspace load to pre-warm the cache).
CREATE INDEX IF NOT EXISTS idx_citation_reasonings_case
    ON citation_reasonings (case_id);
